export enum UserRole {
    SYSTEM_ADMIN = 'SYSTEM_ADMIN',
    ATTENDANCE_ADMIN = 'ATTENDANCE_ADMIN',
    ATTENDANCE_USER = 'ATTENDANCE_USER',
    PROJECT_ADMIN = 'PROJECT_ADMIN',
    PROJECT_USER = 'PROJECT_USER',
    SYSTEM_USER = 'SYSTEM_USER',
}
